### ISSUE TITLE
No handler could be found for the page 'pool%2Flist'

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#1026]
**Server Software**
```
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://[redacted]/index.php?q="

versions:
  shimmie: "2.11.0-alpha-20240208-3e56432"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.22 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 57bd6ea8c66d 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64"
  server: "Unit/1.31.1"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","replace_file","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","autocomplete","bulk_add_csv","emoticons_list","et_server","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories","tag_tools","tagger_xml"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 26532
  comments: 0
  users: 2

media:
  memory_limit: "32MB"
  disk_use: "128GB"
  disk_total: "197GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 190
  height: 300
  scaling: 100
  mime: "image/jpeg"
```

**Client Software (please complete the following information)**
 - Device: macOS 13.6.4 Desktop
 - Browser: Safari 17.3

**What steps trigger this bug**
1. Click "Pools"
2. Click any existing pool (or create a new one)
3. On the pool page, enter a term in the Search field and click go/press enter.

**What did you expect to happen?**
The search should execute and have checkboxes next to each image for adding more to the pool.

**What actually happened?**
`No handler could be found for the page 'pool%2Flist'`

Thanks to the change history, I can see that I haven't added anything to pools since Jan 12, so whatever is impacting this was likely in the last month. Or I'm just doing something wrong.
