### ISSUE TITLE
Search redirects to front page rather than search results

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#1030]
**Server Software**
```
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://[redacted]/index.php?q="

versions:
  shimmie: "v2.10.3-20240211-62ece58"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.22 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux e2b4ff35dcec 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64"
  server: "Unit/1.31.1"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","replace_file","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","autocomplete","bulk_add_csv","emoticons_list","et_server","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories","tag_tools","tagger_xml"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 28132
  comments: 0
  users: 2

media:
  memory_limit: "32MB"
  disk_use: "129GB"
  disk_total: "197GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 190
  height: 300
  scaling: 100
  mime: "image/jpeg"
```

Of note:
 - Front page: home
 - Main page: home
 - Nice URLs: off
 - Among others, Homepage and Autocomplete extensions are enabled

**Client Software (please complete the following information)**
 - Device: macOS Desktop
 - Browser: Safari

**What steps trigger this bug**
1. Attempt any search, either from the home page or from the posts page.

**What did you expect to happen?**
Results list should be shown.

**What actually happened?**
Redirects to the front page.

(Feels somewhat similar to #930 , but this is affecting searches from both the home page and the post search field, and Nice URLs is off)
