### ISSUE TITLE
Undefined constant "Shimmie2\TRUSTED_PROXIES" in /app/core/util.php:155

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#1061]
Cannot get system info since installation cannot finish. Trying to set up a fresh test install using the latest docker image and the following compose file:
```
version: "3"
services:
  sql:
    image: postgres:15-alpine
    container_name: shimmie-tmp-sql
    restart: unless-stopped
    #user: 1000:1000
    environment:
      POSTGRES_USER: shimmie
      POSTGRES_PASSWORD: shimmie
    volumes:
      - db:/var/lib/postgresql/data
      
  shimmie:
    image: shish2k/shimmie2:latest
    container_name: shimmie-tmp
    restart: unless-stopped
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: shimmie
      POSTGRES_PASSWORD: shimmie
      INSTALL_DSN: "pgsql:user=shimmie;password=shimmie;host=sql;dbname=shimmie"
      UPLOAD_MAX_FILESIZE: 2048M
      MAX_FILE_UPLOADS: 1000
    ports:
      - 7001:8000
    volumes:
      - app:/app/data
      - "/mnt/docker/custom/shimmie2-tmp/php/php.ini:/etc/php/8.2/cli/php.ini"

  redis:  
    image: redis
    command: "--port ${CAC_PORT} --maxmemory ${CAC_MAXMEM} --requirepass '${CAC_PW}'"
    container_name: shimmie-tmp-cache
    ports:
      - "9447:9447"

volumes:
  db:
    driver: local
  app: 
    driver: local
```

On the first request, get the following PHP error:
```
2024/02/21 14:38:56 [notice] 64#64 [unit] #10: php message: PHP Fatal error:  Uncaught Error: Undefined constant "Shimmie2\TRUSTED_PROXIES" in /app/core/util.php:155
Stack trace:
#0 /app/core/util.php(170): Shimmie2\is_trusted_proxy()
#1 /app/core/dbengine.php(85): Shimmie2\get_real_ip()
#2 /app/core/database.php(74): Shimmie2\PostgreSQL->init()
#3 /app/core/database.php(212): Shimmie2\Database->get_db()
#4 /app/core/database.php(244): Shimmie2\Database->_execute()
#5 /app/core/database.php(401): Shimmie2\Database->get_all()
#6 /app/core/install.php(219): Shimmie2\Database->count_tables()
#7 /app/core/install.php(80): Shimmie2\create_tables()
#8 /app/core/install.php(49): Shimmie2\do_install()
#9 /app/index.php(28): Shimmie2\install()
#10 {main}
  thrown in /app/core/util.php on line 155
```

Is trusted proxies a new setting which needs to be set for installation? I see that this setting can be defined in /core/sys_config.php, but afaik for a bare minimum install, changing this file or creating /app/data/shimmie_conf.php should not be necessary, correct?
