### ISSUE TITLE
Autocomplete extension not working on individual post pages

### ISSUE THREAD

**Issue by Hawker2** [shish/shimmie2#1151]
**Server Software**
```
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://booru.REDACTED.com/index.php?q="

versions:
  shimmie: "2.11.0-alpha-20240512-5cbbe5e"
  schema: 21
  php: "8.2.18"
  db: "pgsql PostgreSQL 11.22 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 9020bf547b35 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64"
  server: "Unit/1.32.1"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","setup","static_files","system","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","autocomplete","bulk_add_csv","emoticons_list","et_server","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories","tag_tools","tagger_xml"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 33448
  comments: 0
  users: 2

media:
  memory_limit: "128MB"
  disk_use: "132GB"
  disk_total: "197GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 190
  height: 300
  scaling: 100
  mime: "image/jpeg"
```
**Client Software (please complete the following information)**
 - Device: MacBook Air M1, macOS Sonoma 14.4.1
 - Browser: Safari 17.4.1

**What steps trigger this bug**
1. Go to the home screen. Type something in the main search field that should autocomplete. Note that the dropdown appears/works.
2. Go to the main "posts" view. Type something in the upper-left search field that should autocomplete. Note that the dropdown appears/works.
3. Go to any post. Type something in the upper-left search field that should autocomplete.

**What did you expect to happen?**
Unlike the home page and posts/search results page, the autocomplete extension does not trigger for the search field on an individual post page (url of the format "index.php?q=post/view/[id]").

**What actually happened?**
Nothing; behaved as if the autocomplete extension were not loaded. Typing proceeded normally and search worked; just no autocomplete dropdown.
