### ISSUE TITLE
Regression: 2024.09.08 Docker image has left-aligned Danbooru2 homepage

### ISSUE THREAD

**Issue by Hawker2** [shish/shimmie2#1272]
This is in reference to https://hub.docker.com/r/shish2k/shimmie2/ .

**Server Software**
```
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://[redacted]/index.php?q="

versions:
  shimmie: "2.12.0-alpha-20240908-fa2d171"
  schema: 21
  php: "8.2.20"
  db: "pgsql PostgreSQL 11.22 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 33a54fc621fd 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64"
  server: "Unit/1.32.1"

extensions:
  core: ["admin","alias_editor","bbcode","comment","common_elements","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","setup","static_files","system","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","autocomplete","bulk_add_csv","emoticons_list","et_server","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories","tag_tools","tagger_xml"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 41786
  comments: 0
  users: 2

media:
  memory_limit: "128MB"
  disk_use: "148GB"
  disk_total: "197GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 190
  height: 300
  scaling: 100
  mime: "image/jpeg"
```

**Client Software (please complete the following information)**
 - Device: macOS 14.6.1
 - Browser: Safari 17.6, Firefox 125.0.1, Chrome 128

**What steps trigger this bug**
1. Set a site to use the "Danbooru2" theme
2. Update a Docker-based install to use the "latest" image (published 2024/09/08, although there is no corresponding Github release)
3. Open the "home" page

**What did you expect to happen?**
The normal homepage is center-aligned, in keeping with the Danbooru 2 style, and was in previous builds (e.g. 2.11.4).

**What actually happened?**
The homepage is now strangely left-aligned, as shown here:
<img width="830" alt="Danbooru2 Left-Aligned" src="https://github.com/user-attachments/assets/9bd9b700-53b9-4b69-ae9e-98ba4df84a5d">

I'm a bit concerned as there seems to have been an update to the Docker image - with breaking changes - but no corresponding Github release. Is this an intentional update?
