### ISSUE TITLE
Uncaught Error: Call to undefined method Shimmie2\DatabaseConfig::delete()

### ISSUE THREAD

**Issue by hyperdefined** [shish/shimmie2#1515]
Hello,

I moved my shimmie2 instance over to a new server, and I can't seem to get it to work anymore.

I can start shimmie2 with no problems when I first create it. However, when I copy any data (from the data folder via docker), it instantly fails and throws this error below. The data folder contains the images and the config for the database.
```
shimmie2  | 2025/02/24 05:27:51 [notice] 26#26 [unit] #13: php message: PHP Fatal error:  Uncaught Error: Call to undefined method Shimmie2\DatabaseConfig::delete() in /app/ext/image_view_counter/main.php:83
shimmie2  | Stack trace:
shimmie2  | #0 /app/core/send_event.php(161): Shimmie2\ImageViewCounter->onDatabaseUpgrade()
shimmie2  | #1 /app/index.php(75): Shimmie2\send_event()
shimmie2  | #2 {main}
shimmie2  |   thrown in /app/ext/image_view_counter/main.php on line 83
shimmie2  | 2025/02/24 05:28:51 [notice] 24#24 app process 26 exited with code 0
```

```yaml
version: "3.8"
services:
  shimmie:
    image: shish2k/shimmie2:2
    container_name: shimmie2
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:3026:8000
    volumes:
      - ./data:/app/data
    networks:
      - mysql
networks:
  mysql:
    external: true
```

I migrated my database over itself, and I can confirm that is fine. Otherwise telling it to use the database errors out.
