### ISSUE TITLE
"av1" is not a valid backing value for enum Shimmie2\VideoCodec

### ISSUE THREAD

**Issue by gen-angry** [shish/shimmie2#1719]
**Server Software**
```
about:
  title: "stuff"
  theme: "default"
  url: "http://192.168.2.200:26969/"

versions:
  shimmie: "2.12.0-alpha-20250408-83b01ef"
  schema: "21"
  php: "8.4.5"
  db: "sqlite 3.46.1"
  os: "Linux 374be6c71f31 6.11.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 19 16:50:40 UTC 2025 x86_64"
  server: "Unit/1.34.2"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","post_lock","post_owner","post_source","post_tags","replace_file","robots_txt","setup","static_files","system","tag_list","tag_map","upgrade","upload","user","user_config","view"]
  extra: ["bulk_actions","bulk_download","downtime","handle_video","home","random_list","regen_thumb","tag_tools","transcode_video"]
  handled_mimes: [{"base":"image/jpeg","parameters":""},{"base":"image/gif","parameters":""},{"base":"image/png","parameters":""},{"base":"image/webp","parameters":""},{"base":"image/avif","parameters":""},{"base":"video/x-ms-asf","parameters":""},{"base":"video/x-msvideo","parameters":""},{"base":"video/x-flv","parameters":""},{"base":"video/x-matroska","parameters":""},{"base":"video/mp4","parameters":""},{"base":"video/ogg","parameters":""},{"base":"video/quicktime","parameters":""},{"base":"video/webm","parameters":""}]

stats:
  images: 450
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "85GB"
  disk_total: "937GB"

thumbnails:
  engine: "gd"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"
```

 - Shimmie version: 2.12.0-alpha-20250408-83b01ef
 - Database: sqlite
 - Web server: whichever the docker container uses

**Client Software (please complete the following information)**
 - Device: Linudx mint laptop
 - Browser: firefox

**What steps trigger this bug**
1. Upload an AV1 encoded file.
2. Everything breaks.

**What did you expect to happen?**
An error message if the codec isn't supported without breaking the site entirely.

**What actually happened?**

I just get a white screen with this:

```
Internal Error

Message: "av1" is not a valid backing value for enum Shimmie2\VideoCodec

Version: 2.12.0-alpha-20250408-83b01ef (on 8.4.5)

Stack Trace:

#0 /app/ext/handle_video/main.php(35): Shimmie2\VideoCodec::from()
#1 /app/core/Extension/DataHandlerExtension.php(123): Shimmie2\VideoFileHandler->media_check_properties()
#2 /app/core/Events/EventBus.php(159): Shimmie2\DataHandlerExtension->onMediaCheckProperties()
#3 /app/core/Events/EventBus.php(16): Shimmie2\EventBus->send_event()
#4 /app/core/Extension/DataHandlerExtension.php(69): Shimmie2\send_event()
#5 /app/core/Events/EventBus.php(159): Shimmie2\DataHandlerExtension->onDataUpload()
#6 /app/core/Events/EventBus.php(16): Shimmie2\EventBus->send_event()
#7 /app/ext/upload/main.php(293): Shimmie2\send_event()
#8 /app/core/Database/Database.php(107): Shimmie2\Upload->{closure:Shimmie2\Upload::try_upload():292}()
#9 /app/ext/upload/main.php(292): Shimmie2\Database->with_savepoint()
#10 /app/ext/upload/main.php(225): Shimmie2\Upload->try_upload()
#11 /app/core/Events/EventBus.php(159): Shimmie2\Upload->onPageRequest()
#12 /app/core/Events/EventBus.php(16): Shimmie2\EventBus->send_event()
#13 /app/index.php(93): Shimmie2\send_event()
#14 /app/index.php(144): Shimmie2\main()
#15 {main}
```
