### ISSUE TITLE
Image replace throws error

### ISSUE THREAD

**Issue by damjess** [shish/shimmie2#735]
**Server Software**
```
about:
   theme: "customtheme"

versions:
  shimmie: "2.8.4+"
  schema: 19
  php: "7.4.7"
  db: "pgsql PostgreSQL 11.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit"
  os: "Linux [ip-details] #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64"
  server: "Apache/2.4.38 (Debian)"

extensions:
  core: ["alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["admin","autocomplete","ban_words","danbooru_api","favorites","featured","handle_cbz","handle_flash","handle_ico","handle_svg","handle_video","image_hash_ban","image_view_counter","ipban","link_image","notes","numeric_score","random_image","random_list","rating","regen_thumb","relationships","report_image","res_limit","rotate","site_description","source_history","tag_categories","tag_editcloud","trash","wiki"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","application/vnd.comicbook+zip","application/x-shockwave-flash","image/x-icon","application/riff+ani","image/x-win-bitmap","image/vnd.microsoft.icon","image/svg+xml","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

stats:
  images: 50
  comments: 1
  users: 15

media:
  memory_limit: "8.0MB"
  disk_use: "1.9GB"
  disk_total: "7.7GB"

thumbnails:
  engine: "gd"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: "3297e716"
  branch: "custombranch"
  origin: "https://github.com/shish/shimmie2"

```
**Client Software (please complete the following information)**
 - Device: desktop
 - Browser: Safari Version 13.1.1

**What steps trigger this bug**
1. Go to 'Posts'
2. Click on any image
3. Click 'replace' 
4. Select image as replacement upload from computer
5. Click 'post'

**What did you expect to happen?**
Click 'post' and the image should get replaced.

**What actually happened?**
500 on page. Reloading the booru and see the image has not been replaced, stack trace in error log:
```
PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /path/to/shimmie2/ext/upload/main.php on line 335, referer: https://mydomain.com/upload/replace/55
PHP Notice:  Trying to access array offset on value of type int in /path/to/shimmie2/ext/upload/main.php on line 348, referer: https://mydomain.com/upload/replace/55
PHP Notice:  Trying to access array offset on value of type int in /path/to/shimmie2/ext/upload/main.php on line 349, referer: https://mydomain.com/upload/replace/55
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Upload::upload_error_message() must be of the type int, null given, called in /path/to/shimmie2/ext/upload/main.php on line 349 and defined in /path/to/shimmie2/ext/upload/main.php:296\nStack trace:\n#0 /path/to/shimmie2/ext/upload/main.php(349): Upload->upload_error_message()\n#1 /path/to/shimmie2/ext/upload/main.php(221): Upload->try_upload()\n#2 /path/to/shimmie2/core/send_event.php(113): Upload->onPageRequest()\n#3 /path/to/shimmie2/index.php(82): send_event()\n#4 {main}\n  thrown in /path/to/shimmie2/ext/upload/main.php on line 296, referer: https://mydomain.com/upload/replace/55
```

Thanks for all the help, you're very fast to respond and we really appreciate it!
