### ISSUE TITLE
Autocomplete doesn`t work (404 error)

### ISSUE THREAD

**Issue by ka1tzyu** [shish/shimmie2#751]
Autocomplete doesn`t work and give it in console:
![chrome_BhfsAStBOs](https://user-images.githubusercontent.com/56955307/92996288-290b1f80-f513-11ea-9ea7-6feea6564a03.png)

My SystemInfo:
```
about:
  title: "xshimmie"
  theme: "danbooru2_red"
  url: "http://localhost/index.php?q="

versions:
  shimmie: "2.8.4+"
  schema: 19
  php: "7.4.3"
  db: "mysql 8.0.21-0ubuntu0.20.04.4"
  os: "Linux DESKTOP-DBCO6T9 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64"
  server: "Apache/2.4.41 (Ubuntu)"

extensions:
  core: ["alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["admin","artists","autocomplete","bulk_actions","downtime","favorites","handle_cbz","handle_flash","handle_ico","handle_mp3","handle_svg","handle_video","home","image_view_counter","ipban","numeric_score","pools","rating","regen_thumb","report_image","resize","site_description","update","wiki"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp","application/vnd.comicbook+zip","application/x-shockwave-flash","image/x-icon","application/riff+ani","image/x-win-bitmap","image/vnd.microsoft.icon","audio/mpeg","image/svg+xml","video/x-ms-asf","video/x-msvideo","video/x-flv","video/x-matroska","video/mp4","video/ogg","video/quicktime","video/webm"]

stats:
  images: 173
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "17.5GB"
  disk_total: "251.0GB"

thumbnails:
  engine: "gd"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: "988bc831"
  branch: "master"
  origin: "https://github.com/shish/shimmie2"


```
