### ISSUE TITLE
Please improve Docker documentation, especially for first install and database setup

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#913]
**Is your feature request related to a problem? Please describe.**
Documentation (especially for Docker) could use some improvement. Especially basics like first-time setup and database dependencies.

**Describe the solution you'd like**
For the Docker install, include a full compose file that can start the project in one go - including the database! While many folks are familiar with setting up a simple SQL database, many are not, and it goes against the spirit of compose to have an external dependency that's not documented.

Additionally, when setting up the database from the first-run screen (i.e. without the DSN), add a test button/function to verify it works _before_ leaving that screen. Similar to how Grafana adds data sources.

For instance, you'd be more than welcome to use mine:
```
version: "3"
services:
  sql:
    image: postgres:11-alpine
    container_name: shimmie-sql
    restart: unless-stopped
    user: 1000:1000
    environment:
      POSTGRES_USER: shimmie
      POSTGRES_PASSWORD: shimmie
    volumes:
      - ./db:/var/lib/postgresql/data
  shimmie:
    image: shish2k/shimmie2:latest
    container_name: shimmie
    restart: unless-stopped
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: shimmie
      POSTGRES_PASSWORD: shimmie
      INSTALL_DSN: "pgsql:user=shimmie;password=shimmie;host=sql;dbname=shimmie"
    ports:
      - 8001:8000
    volumes:
      - ./data:/app/data
```
Just point out the weak username/password on the database above, and this should be a passable starter.

**Describe alternatives you've considered**
I've been documenting my install as I go on, but that doesn't benefit anyone but me. :)
