### ISSUE TITLE
Please add documentation on adjusting maximum upload sizes for Docker install

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#915]
**Server Software**
```
about:
  title: "HomeBooru"
  theme: "danbooru2"

versions:
  shimmie: "2.10.0-alpha"
  schema: 21
  php: "8.2.5"
  db: "pgsql PostgreSQL 11.20 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit"
  os: "Linux 4d65c90ec21a 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64"
  server: "PHP 8.2.5 Development Server"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["favorites","home","pools","random_image","random_list","rating","regen_thumb","relationships","tag_categories"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 0
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "131.6GB"
  disk_total: "196.7GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 256
  height: 256
  scaling: 100
  mime: "image/jpeg"
```
 - Database: postgres
 - Web server: Docker container built-in

**What steps trigger this bug**
1. Although the "Board Config" UI calls out various PHP limitations on uploads, it is not at all clear how to change these in the Docker container.
2. The "Board Config" page lists two limits (Max Uploads, Max Size Per File); are there any others?
3. Since the Docker image also includes a built-in web server (which?) we probably need documentation on how to increase its post limits as well.

Documentation is sparse to non-existent for handling larger files (whether large images, video clips, CBR files, etc).

**What did you expect to happen?**
I expected some documentation on how to change this very common setting.
