### ISSUE TITLE
[lighttpd] 404 when searching rating:? using Nice URLs 

### ISSUE THREAD

**Issue by luanalatte** [shish/shimmie2#929]
**Server Software**
```
about:
  title: "sugarynips' booru"
  theme: "default"
  url: "http://192.168.0.11/"

versions:
  shimmie: "2.10.0-alpha+"
  schema: 21
  php: "8.2.7"
  db: "sqlite 3.40.1"
  os: "Linux debian 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64"
  server: "lighttpd/1.4.69"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["approval","auto_tagger","autocomplete","blocks","bulk_actions","custom_html_headers","emoticons","emoticons_list","favorites","featured","home","rating","relationships","tag_categories","wiki"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 149
  comments: 2
  users: 4

media:
  memory_limit: "8.0MB"
  disk_use: "13.6GB"
  disk_total: "263.4GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: ""
  branch: ""
  origin: ""
```
 
**What did you expect to happen?**
Should rewrite to `/index.php?q=post/list&search=rating%3A%3F`, if im not mistaken.

**What actually happened?**
I get a 404 and the current URL on the browser looks like this `/post/list?search=rating%3A%3F&q=%2Fpost%2Flist`

I tried many combinations of settings on lighttpd rewrites, but I keep getting the same error. I suspect it has something to do with the question mark, but that should be being escaped, right? The duplicate /post/list is making me think it could be a bug on the search rather than a config mistake on lighttpd.

Here's some of the rewrite rules I tried:

`"^(?!/phpmyadmin)([^\?]+)(\?(.*))?" => "/index.php?q=$1&$3"` This one worked a couple years ago.

`"^([^\?]+)(?:\?(.*))?" => "/index.php?q=$1&$2"` This is a simplified version of the previous one.

`"" => "/index.php?q=${url.path}${qsa}"` This is using the latest lighttpd features. Not quite sure if it is correct, though.

I apologize in advance if this is a mistake on my part. Maybe someone can help me find that mistake, and I can update our lighttpd wiki page.
