### ISSUE TITLE
Images corrupted when moving VPSes

### ISSUE THREAD

**Issue by HaveANiceDay21** [shish/shimmie2#935]
I'm moving VPSes and I transfer all the files via FTP and the mysql database to the new one and all images and videos do not load when I click on the posts. Thumbnails are working, only the posts that are in JPEG actually load while the others don't. Everything else works fine though.

```
about:
  title: "testbooru"
  theme: "lite"
  url: "https://my.site/index.php?q="

versions:
  shimmie: "2.10.0-alpha+"
  schema: 21
  php: "8.1.20"
  db: "mysql 8.0.33"
  os: "Linux my.site 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64"
  server: "nginx/1.18.0"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["approval","auto_tagger","autocomplete","biography","browser_search","bulk_actions","bulk_add","bulk_add_csv","bulk_download","bulk_import_export","danbooru_api","downtime","emoticons","emoticons_list","favorites","handle_archive","handle_cbz","handle_flash","handle_ico","handle_mp3","handle_svg","handle_video","home","image_view_counter","ipban","link_image","not_a_tag","pm","pools","post_titles","random_image","random_list","rating","report_image","rss_comments","rss_images","site_description","tag_categories","tag_editcloud","tag_history","tag_tools","wiki"]
  handled_mimes: {"0":"image/jpeg","1":"image/gif","2":"image/png","3":"image/webp","4":"application/zip","6":"application/vnd.comicbook+zip","7":"application/x-shockwave-flash","8":"image/x-icon","9":"application/riff+ani","10":"image/x-win-bitmap","11":"image/vnd.microsoft.icon","12":"audio/mpeg","13":"image/svg+xml","14":"video/x-ms-asf","15":"video/x-msvideo","16":"video/x-flv","17":"video/x-matroska","18":"video/mp4","19":"video/ogg","20":"video/quicktime","21":"video/webm"}

stats:
  images: 162
  comments: 30
  users: 12

media:
  memory_limit: "50.0MB"
  disk_use: "83.1GB"
  disk_total: "99.3GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: "b5b7fe7d"
  branch: "master"
  origin: "https://github.com/shish/shimmie2"

```
