### ISSUE TITLE
Pool list breaks when sorting by last updated

### ISSUE THREAD

**Issue by luanalatte** [shish/shimmie2#942]
**Server Software**
```
about:
  title: "Shimmie"
  theme: "default"
  url: "http://localhost/index.php?q="

versions:
  shimmie: "2.10.0-alpha+"
  schema: 21
  php: "8.2.7"
  db: "sqlite 3.42.0"
  os: "Linux arch 6.4.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 x86_64"
  server: "lighttpd/1.4.71"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["approval","blocks","bulk_actions","home","pools","rating"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 3
  comments: 0
  users: 3

media:
  memory_limit: "8.0MB"
  disk_use: "373.8GB"
  disk_total: "817.1GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"

git:
  commit: ""
  branch: ""
  origin: ""
```

**Client Software (please complete the following information)**
 - Device: Linux Desktop
 - Browser: Firefox

**What steps trigger this bug**
1. Go to /pool/list.
2. Order pools by Last Updated.

**What actually happened?**
```
Internal Error

Message: SQLSTATE[HY000]: General error: 1 no such column: p.lastupdated

Query:

Version: 2.10.0-alpha+ (on 8.2.7)

Stack Trace:

#0 /srv/http/core/database.php(193): Shimmie2\Database->_execute()
#1 /srv/http/ext/pools/main.php(633): Shimmie2\Database->get_all()
#2 /srv/http/ext/pools/main.php(224): Shimmie2\Pools->list_pools()
#3 /srv/http/core/send_event.php(153): Shimmie2\Pools->onPageRequest()
#4 /srv/http/index.php(86): Shimmie2\send_event()
#5 {main}
```

**Workaround**
Delete site cookies to rever to default order by Recently created.

**Extra information**
This also happens in my actual booru which is some amount of commits behind, and running on nginx instead of lighttpd. Both are running sqlite.
