### ISSUE TITLE
Tag editing field could be quite a bit larger

### ISSUE THREAD

**Issue by diamondsw** [shish/shimmie2#943]
**Is your feature request related to a problem? Please describe.**
When editing tags, the current tag field is extremely small - only a single tag typically fits in it, and if you're trying to edit something near the middle - for instance, to remove a tag that shouldn't be there - it's very difficult to work with.

**Describe the solution you'd like**
A larger multiline field - ideally resizable - perhaps similar in size to the comment field.

**Describe alternatives you've considered**
Lots of arrowing. Lots and lots of arrowing.

**Additional context**
Screenshot: https://imgur.com/a/aAkl3gU
(Tiny!)

**Comment by shish** [comment]
I am unable to reproduce this - trying with various themes, and with the autocomplete extension both enabled or disabled, the tag edit field is always the same size as the other fields :S

If it's still an issue, feel free to reopen with extra info of which theme and extensions you're using

**Comment by diamondsw** [comment]
Sure. This happens in Safari on macOS; after your comment I checked Chrome on macOS, and indeed it does not happen there. So I can see why this would be hard to reproduce (I have no idea why Safari is treating that lone field differently from the others.

However, even if the field is the same size as the others, that doesn't necessarily reflect the amount of content that may be in it. The other editable fields have - by and large - a single item in them, but the tags field is open-ended in terms of length. As such, I'd still argue it should be a much larger field than the others - multiple lines with word wrap, and ideally resizable.

Heh, kind of like the issue field I'm typing in right now. Supports multiple lines with word wrap, and is resizable if I need more room.

As far as my configuration goes (although I think we've nailed down the discrepancy to Safari):
```
about:
  title: "HomeBooru"
  theme: "danbooru2"
  url: "http://booru.redacted.com/index.php?q="

versions:
  shimmie: "2.10.0-alpha"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 11.21 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit"
  os: "Linux 989667cbfe21 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64"
  server: "PHP 8.2.7 Development Server"

extensions:
  core: ["admin","alias_editor","bbcode","comment","download","et","ext_manager","four_oh_four","handle_pixel","help_pages","image","index","media","mime","setup","static_files","system","tag_edit","tag_list","upgrade","upload","user","user_config","view"]
  extra: ["auto_tagger","bulk_add_csv","favorites","home","pools","post_titles","random_image","random_list","rating","regen_thumb","relationships","tag_categories"]
  handled_mimes: ["image/jpeg","image/gif","image/png","image/webp"]

stats:
  images: 19236
  comments: 0
  users: 2

media:
  memory_limit: "8.0MB"
  disk_use: "182.3GB"
  disk_total: "196.7GB"

thumbnails:
  engine: "convert"
  quality: 75
  width: 192
  height: 192
  scaling: 100
  mime: "image/jpeg"
```
