### ISSUE TITLE
cannot use redis or memcached

### ISSUE THREAD

**Issue by Giraffaman** [shish/shimmie2#997]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

  shimmie: "2.10.0-beta2-20240107-e401dd9"
  schema: 21
  php: "8.2.7"
  db: "pgsql PostgreSQL 15.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
  os: "Linux 84d8f74c3c9b 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64"
  server: "Unit/1.31.1"

**What steps trigger this bug**
1. Run a basic docker-compose deployment with either a redis or memcached container in it:
```
version: "3"
services:
  sql:
    image: postgres:15-alpine
    container_name: shimmie-tmp-sql
    restart: unless-stopped
    #user: 1000:1000
    environment:
      POSTGRES_USER: shimmie
      POSTGRES_PASSWORD: shimmie
    volumes:
      - db:/var/lib/postgresql/data
      
  shimmie:
    image: shish2k/shimmie2:latest
    container_name: shimmie-tmp
    restart: unless-stopped
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: shimmie
      POSTGRES_PASSWORD: shimmie
      INSTALL_DSN: "pgsql:user=shimmie;password=shimmie;host=sql;dbname=shimmie"
    ports:
      - 7001:8000
    volumes:
      - app:/app/data

  redis:  
    image: redis
    container_name: shimmie-tmp-cache
    ports:
      - "6379:6379"

# or memcached
#  cache:
#    image: memcached:latest
#    container_name: shimmie-tmp-cache
#    ports:
#      - 9445:11211
#    command:
#      - '--memory-limit=128'

volumes:
  db:
    driver: local
  app: 
    driver: local
```
2. configure shimmie.conf.php accordingly:
`define('CACHE_DSN', 'redis://shimmie-tmp-cache:6379');`
or
`define("CACHE_DSN", "memcache://shimmie-dev-cache:9445");`
3. try to connect

**What actually happened?**
HTTP 500 when trying to connect to Shimmie and the following log entries:
using redis:
```
2024/01/07 17:19:55 [notice] 65#65 [unit] #13: php message: PHP Fatal error:  Uncaught Predis\Response\ServerException: ERR invalid expire time in 'setex' command in /app/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /app/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse()
#1 /app/vendor/predis/predis/src/Client.php(313): Predis\Client->executeCommand()
#2 /app/vendor/naroga/redis-cache/Redis.php(79): Predis\Client->__call()
#3 /app/core/cacheengine.php(49): Naroga\RedisCache\Redis->set()
#4 /app/core/polyfills.php(806): Shimmie2\EventTracingCache->set()
#5 /app/core/config.php(282): Shimmie2\cache_get_or_set()
#6 /app/index.php(52): Shimmie2\DatabaseConfig->__construct()
#7 {main}
  thrown in /app/vendor/predis/predis/src/Client.php on line 370
```

using memcached:

```
2024/01/07 14:29:15 [notice] 63#63 [unit] #10: php message: PHP Fatal error:  Uncaught Error: Class "Memcached" not found in /app/core/cacheengine.php:110
Stack trace:
#0 /app/index.php(50): Shimmie2\loadCache()
#1 {main}
  thrown in /app/core/cacheengine.php on line 110
```

For redis it seems that it has a problem with a TTL of 0 - I'm not using a config file currently and so redis is running with default settings, but as I understand it there is no setting in the config file that does what the EXPIRE command does. Also tried launching redis with `--maxmemory 256mb --maxmemory-policy allkeys-lru` which should eliminate the need for setting a TTL using the EXPIRE command on every key, but I'm assuming the error occurs because setex is called in the code with either no TTL or a TTL of 0?

For memcached, the error occurs as soon as CACHE_DSN is defined in shimmie.conf.php, no matter which config I try.
